# -*- coding: utf-8 -*-
"""Data_extraction_and_plot_for_the_mitosis_simulations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C8I84MSVt40704tssxZxSz_LJm4ygtqy
"""

from google.colab import files
uploaded = files.upload()

import numpy as np
import matplotlib.pyplot as plt

def read_file(filename):
  number_MCS = 1500
  mcs=[]
  param=[]
  with open(filename, "r") as f:
    for line in f:
      if line.startswith("#"):
        continue
      else:
        parts=line.strip().split()
        Step, E = None, None
        Step = int(parts[0])
        E = float(parts[1])
        if Step > number_MCS:
          break
        else:
          mcs.append(Step)
          param.append(E)
  return mcs, param

mcs_adhesion, energy_adhesion = read_file("adhesion_energy.txt")
mcs_volume, energy_volume = read_file("volume_energy.txt")
mcs_total, energy_total = read_file("total_energy.txt")
mcs_cells, number_of_cells = read_file("cells_counter.txt")
mcs_mean_volume, mean_volume = read_file("mean_volume.txt")
mcs_mean_pressure, mean_pressure = read_file("mean_pressure.txt")
print(mcs_adhesion)

'''
plt.figure(figsize=(13,6))
plt.plot(mcs_total, energy_total, marker= 'o', markersize = 0, linestyle = '-', linewidth = 0.5, color = 'green', label = 'Total Energy')
plt.axhline(y=mean_total_energy, color = 'red', linestyle = '-', linewidth = 1.5, label = f'Mean Energy = {mean_total_energy:.0f}')
plt.xlabel('MCS')
plt.ylabel('Total Energy')
plt.legend()
plt.grid(True)

plt.savefig("Total_Energy_vs_MCS.png", dpi=300)

plt.show()

files.download("Total_Energy_vs_MCS.png")
'''

plt.figure(figsize=(12,9))

plt.plot(mcs_total, energy_total, marker= 'o', markersize = 0, linestyle = '-', linewidth = 2, color = 'green', label = 'Total Energy')
plt.plot(mcs_adhesion, energy_adhesion, marker= 'o', markersize = 0, linestyle = '-', linewidth = 2, color = 'red', label = 'Adhesion Energy')
plt.plot(mcs_volume, energy_volume, marker= 'o', markersize = 0, linestyle = '-', linewidth = 2, color = 'blue', label = 'Volume Energy')

plt.xlabel('MCS')
plt.ylabel('Energy')
plt.legend()
plt.grid(True)

plt.savefig("Energies_vs_MCS.png", dpi=300)

plt.show()

files.download("Energies_vs_MCS.png")

plt.figure(figsize=(12,9))

plt.plot(mcs_cells, number_of_cells, marker= 'o', markersize = 0, linestyle = '-', linewidth = 2, color = 'orange', label = 'Number of cells')

plt.xlabel('MCS')
plt.ylabel('Number of cells')
plt.legend()
plt.grid(True)

plt.savefig("Number_of_cells_vs_MCS.png", dpi=300)

plt.show()

files.download("Number_of_cells_vs_MCS.png")

plt.figure(figsize=(12,9))

plt.plot(mcs_mean_volume, mean_volume, marker= 'o', markersize = 0, linestyle = '-', linewidth = 2, color = 'navy', label = 'Mean Volume')

plt.xlabel('MCS')
plt.ylabel('Mean Volume')
plt.legend()
plt.grid(True)

plt.savefig("Mean_volume_vs_MCS.png", dpi=300)

plt.show()

files.download("Mean_volume_vs_MCS.png")

plt.figure(figsize=(12,9))

plt.plot(mcs_mean_pressure, mean_pressure, marker= 'o', markersize = 0, linestyle = '-', linewidth = 2, color = 'darkviolet', label = 'Mean Pressure')

plt.xlabel('MCS')
plt.ylabel('Mean Pressure')
plt.legend()
plt.grid(True)

plt.savefig("Mean_pressure_vs_MCS.png", dpi=300)

plt.show()

files.download("Mean_pressure_vs_MCS.png")

import os

def delete(filename):
  if os.path.exists(filename):
    os.remove(filename)
    print (f'{filename} correctly removed')
  else:
    print(f'{filename} not found')
  print('------------------------------')

delete("adhesion_energy.txt")
delete("volume_energy.txt")
delete("total_energy.txt")
delete("cells_counter.txt")
delete("mean_volume.txt")
delete("mean_pressure.txt")