# -*- coding: utf-8 -*-
"""Diffusion_Tests_Plots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19VsKENfqnh2q8XDyHCCDiPsQKAJj6bQO

### **DIFFUSION TESTS DATA PLOTS**
"""

from google.colab import files
uploaded = files.upload()

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

MAX_MCS = 200000

def read_COM_file(filename):
    mcs = []
    x1 = []; y1 = []; z1 = []
    x2 = []; y2 = []; z2 = []
    x3 = []; y3 = []; z3 = []

    with open(filename, "r") as f:
        for line in f:
            if line.startswith("#"):
                continue
            parts = line.strip().split()
            step = int(parts[0])
            if step > MAX_MCS:
                break
            mcs.append(step)
            x1.append(float(parts[1])); y1.append(float(parts[2])); z1.append(float(parts[3]))
            x2.append(float(parts[4])); y2.append(float(parts[5])); z2.append(float(parts[6]))
            x3.append(float(parts[7])); y3.append(float(parts[8])); z3.append(float(parts[9]))

    return np.array(mcs), np.array(x1), np.array(y1), np.array(z1), \
           np.array(x2), np.array(y2), np.array(z2), \
           np.array(x3), np.array(y3), np.array(z3)

def read_diffusion_file(filename):
    mcs = []
    VS1 = []; VS2 = []; VS3 = []; VS_mean = []
    L1 = []; L2 = []; L3 = []; L_mean = []

    with open(filename, "r") as f:
        for line in f:
            if line.startswith("#"):
                continue
            parts = line.strip().split()
            step = int(parts[0])
            if step > MAX_MCS:
                break
            mcs.append(step)
            VS1.append(float(parts[1])); VS2.append(float(parts[2])); VS3.append(float(parts[3]))
            VS_mean.append(float(parts[4]))
            L1.append(float(parts[5])); L2.append(float(parts[6])); L3.append(float(parts[7]))
            L_mean.append(float(parts[8]))

    return np.array(mcs), np.array(VS1), np.array(VS2), np.array(VS3), np.array(VS_mean), \
           np.array(L1), np.array(L2), np.array(L3), np.array(L_mean)

# DATA LOADING

mcs_COM, x1, y1, z1, x2, y2, z2, x3, y3, z3 = read_COM_file("COM_positions.txt")
mcs_D, VS1, VS2, VS3, VS_mean, L1, L2, L3, L_mean = read_diffusion_file("Diffusion_tracker.txt")

# CONSISTENT COLORS

colors = ["red", "green", "blue","black"]

# FUNCTION TO AVOID STRAIGHT LINES BECAUSE OF PERIODIC CONDITIONS

def plot_periodic(ax, x, y, z, color, label, L):
    # We add an empty entry to generate the legend
    ax.plot([], [], [], color=color, linewidth=2, label=label)

    for i in range(1, len(x)):
        dx = abs(x[i] - x[i-1])
        dy = abs(y[i] - y[i-1])
        dz = abs(z[i] - z[i-1])

        # If the evolution is small (does not cross the periodic border), we draw the segment
        if dx < L/2 and dy < L/2 and dz < L/2:
            ax.plot(
                [x[i-1], x[i]],
                [y[i-1], y[i]],
                [z[i-1], z[i]],
                color=color,
                linewidth=0.5
            )

# 3D TRAJECTORY DIAGRAM

fig = plt.figure(figsize=(10,10))
ax = fig.add_subplot(111, projection='3d')

L = 100  # tamaño del lattice

plot_periodic(ax, x1, y1, z1, colors[0], "Cell 1", L)
plot_periodic(ax, x2, y2, z2, colors[1], "Cell 2", L)
plot_periodic(ax, x3, y3, z3, colors[2], "Cell 3", L)

ax.set_xlabel("X", fontsize=16)
ax.set_ylabel("Y", fontsize=16)
ax.set_zlabel("Z", fontsize=16)
ax.set_title("3D cells trajectories", fontsize=18)
ax.legend(fontsize=14)

plt.tight_layout()
plt.savefig("3D_trajectories.png", dpi=300)
plt.show()
files.download("3D_trajectories.png")

# PLOT OF TRAVELED DISTANCE

plt.figure(figsize=(12,9))

plt.plot(mcs_D, L1, linewidth=0.5, color=colors[0], label="Cell 1")
plt.plot(mcs_D, L2, linewidth=0.5, color=colors[1], label="Cell 2")
plt.plot(mcs_D, L3, linewidth=0.5, color=colors[2], label="Cell 3")
plt.plot(mcs_D, L_mean, linestyle="--", linewidth=0.5, color=colors[3], label="Mean")

plt.xlabel("MCS", fontsize=22)
plt.ylabel("Traveled distance", fontsize=22)
plt.title("Traveled distance vs MCS", fontsize=24)

leg = plt.legend(fontsize=20)
for line in leg.get_lines():
    line.set_linewidth(2)

plt.grid(True)
plt.xticks(fontsize=18)
plt.yticks(fontsize=18)

plt.savefig("Traveled_distance_vs_MCS.png", dpi=300)

plt.show()

files.download("Traveled_distance_vs_MCS.png")

# PLOT OF V/S RELATION

plt.figure(figsize=(12,9))

plt.plot(mcs_D, VS1, linewidth=0.5, color=colors[0], label="Cell 1")
plt.plot(mcs_D, VS2, linewidth=0.5, color=colors[1], label="Cell 2")
plt.plot(mcs_D, VS3, linewidth=0.5, color=colors[2], label="Cell 3")
plt.plot(mcs_D, VS_mean, linestyle="--", linewidth=0.5, color=colors[3], label="Mean")

plt.xlabel("MCS", fontsize=22)
plt.ylabel("V/S relation", fontsize=22)
plt.title("V/S relation vs MCS", fontsize=24)

leg = plt.legend(fontsize=20)
for line in leg.get_lines():
    line.set_linewidth(2)

plt.grid(True)
plt.xticks(fontsize=18)
plt.yticks(fontsize=18)

plt.savefig("V-S_relation_vs_MCS.png", dpi=300)

plt.show()

files.download("V-S_relation_vs_MCS.png")

# DELETE UPLOADED FILES

import os

def delete(filename):
    if os.path.exists(filename):
        os.remove(filename)
        print(f"{filename} removed")
    else:
        print(f"{filename} not found")
    print("------------------------------")

delete("COM_positions.txt")
delete("Diffusion_tracker.txt")